# Generated by Django 2.2.5 on 2019-11-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191107_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=4096, null=True, verbose_name='Последнне прочитанное сообщение'),
        ),
    ]
