# Generated by Django 2.2.5 on 2019-12-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20191203_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='url',
            new_name='file',
        ),
    ]
