# Generated by Django 2.2.5 on 2019-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191203_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
