# Generated by Django 2.2.5 on 2019-12-10 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20191203_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time and Date of sending'),
        ),
    ]
