# Generated by Django 2.2.5 on 2019-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('nick', models.CharField(blank=True, max_length=16)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
            ],
        ),
    ]
