# Generated by Django 2.2.5 on 2019-11-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191107_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick',
        ),
    ]
